# Generated by Django 6.1.1 on 2026-09-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='dark_mode',
        ),
    ]
